#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=: read -r username password uid gid info homedir shell;
do
    gang=$(grep -E "^.*:x:$gid:" /etc/group | cut -d: -f1)
    passcode=$(echo "$password" | awk -F'$' '{print $2}')
    printf "The user %s is part of the %s gang, lives in %s and rides %s.\n" "$username" "$gid" "$homedir" "$shell"
    printf "User ID's place is protected by the passcode %s, more info about the user here: %s\n\n" "$passcode" "$username"
done < /etc/passwd
