#!/usr/bin/env bash
#script that displays the content of the file /etc/passwd, using the while loop + IFS
while IFS=: read -r username _ uid gid info home shell;
do
IFS=',' read -ra id_info <<< "$info"
IFS='/' read -ra shell_parts <<< "$shell"
passcode="${shell_parts[-1]}"
echo "The user $username is part of the $gid gang, lives in $home and rides ${shell_parts[0]}."
echo "User ID's place is protected by the passcode $passcode, more info about the user here: ${id_info[*]}"
echo
done < /etc/passwd
