#!/usr/bin/env bash
#script that does alot
PID_FILE="/var/run/my_process.pid"
PROCESS_SCRIPT="./manage_my_process"

start() {
    if [ -f "$PID_FILE" ]; then
        echo "manage_my_process is already running"
    else
        $PROCESS_SCRIPT &
        echo $! > "$PID_FILE"
        echo "manage_my_process started"
    fi
}

stop() {
    if [ -f "$PID_FILE" ]; then
        pid=$(cat "$PID_FILE")
        kill "$pid"
        rm "$PID_FILE"
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
}

restart() {
  echo "manage_my_process restarted"
}

case $1 in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
