#!/usr/bin/env bash
#script that; indefinitely writes I am alive! to the file /tmp/my_process
#In between every I am alive! message, the program should pause for 2 seconds
b=1
while [ $b -ge 1 ]
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
